"""Update floor table

Revision ID: 14d6b9176046
Revises: bf82e307f55f
Create Date: 2026-01-03 23:50:09.894014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d6b9176046'
down_revision = 'bf82e307f55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.alter_column('map_img_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.alter_column('map_img_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
