"""Initial Migration

Revision ID: 227e73fc4e22
Revises: 
Create Date: 2026-01-01 02:10:55.398321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227e73fc4e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('building_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('ml_model',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('floor',
    sa.Column('floor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('map_img_url', sa.String(length=255), nullable=True),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('origin_x', sa.Float(), nullable=False),
    sa.Column('origin_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.PrimaryKeyConstraint('floor_id')
    )
    op.create_table('node',
    sa.Column('node_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('x_coordinate', sa.Float(), nullable=False),
    sa.Column('y_coordinate', sa.Float(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.floor_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('edge',
    sa.Column('edge_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_node_id', sa.Integer(), nullable=False),
    sa.Column('end_node_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('is_walkable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['end_node_id'], ['node.node_id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.floor_id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['node.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_table('localization_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('predicted_node_id', sa.Integer(), nullable=False),
    sa.Column('actual_node_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actual_node_id'], ['node.node_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_model.model_id'], ),
    sa.ForeignKeyConstraint(['predicted_node_id'], ['node.node_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('mg__fingerprint',
    sa.Column('fingerprint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('mean_x', sa.Float(), nullable=False),
    sa.Column('mean_y', sa.Float(), nullable=False),
    sa.Column('mean_z', sa.Float(), nullable=False),
    sa.Column('std_x', sa.Float(), nullable=False),
    sa.Column('std_y', sa.Float(), nullable=False),
    sa.Column('std_z', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.node_id'], ),
    sa.PrimaryKeyConstraint('fingerprint_id')
    )
    op.create_table('mg_session',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.node_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('mg__raw__reading',
    sa.Column('reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('mag_x', sa.Float(), nullable=False),
    sa.Column('mag_y', sa.Float(), nullable=False),
    sa.Column('mag_z', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mg_session.session_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mg__raw__reading')
    op.drop_table('mg_session')
    op.drop_table('mg__fingerprint')
    op.drop_table('localization_log')
    op.drop_table('edge')
    op.drop_table('node')
    op.drop_table('floor')
    op.drop_table('user')
    op.drop_table('ml_model')
    op.drop_table('building')
    # ### end Alembic commands ###
