"""Update Mg_session table

Revision ID: 30cb288df5a3
Revises: d2cc79c1f9ce
Create Date: 2025-12-31 06:24:06.365498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cb288df5a3'
down_revision = 'd2cc79c1f9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mg_session', schema=None) as batch_op:
        batch_op.drop_column('started_at')
        batch_op.drop_column('device_id')
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mg_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('device_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
