"""Added Edge Type

Revision ID: 67e40c6a1429
Revises: 14d6b9176046
Create Date: 2026-03-05 21:16:53.495831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e40c6a1429'
down_revision = '14d6b9176046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edge_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.drop_column('edge_type')

    # ### end Alembic commands ###
