"""Change Floor Table

Revision ID: bf82e307f55f
Revises: e63731c3e20e
Create Date: 2026-01-01 02:33:19.428237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf82e307f55f'
down_revision = 'e63731c3e20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.alter_column('map_img_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floor', schema=None) as batch_op:
        batch_op.alter_column('map_img_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
